POST http://localhost:5000/log-in
Content-Type: application/json

{
  "username": "SampleUser",
  "password": "Password"
}

###

GET http://localhost:5000/sets/72
Accept: application/json

###


POST http://localhost:5000/set/create
Content-Type: application/json

{
  "workoutID": "1",
  "warmUp": "false",
  "rest": "00:02:02",
  "reps": "5",
  "intensity": "3",
  "notes": "Tough set",
  "exerciseName": "BenchPress"
}

###

POST http://localhost:5000/set/create
Content-Type: application/json

{
  "workoutID": "3",
  "warmUp": "true",
  "rest": "00:02:02",
  "reps": "5",
  "intensity": "3",
  "notes": "Tough set",
  "exerciseName": "BenchPress"
}

###

GET http://localhost:5000/set/1/BenchPress/3

###

GET http://localhost:5000/sets/1/BenchPress

###

POST http://localhost:5000/set/update
Content-Type: application/json

{
  "workoutID": "1",
  "warmUp": "true",
  "rest": "00:00:05",
  "reps": "8",
  "intensity": "3",
  "notes": "Tough set",
  "exerciseName": "BenchPress",
  "setNumber": "5"
}

###

POST http://localhost:5000/set/delete
Content-Type: application/json

{
  "workoutID": "1",
  "setNumber": "5",
  "exerciseName": "BenchPress"
}

###


