POST http://localhost:5000/workout/create
Content-Type: application/json

{
  "date": "10/22/2023"
}

###
POST http://localhost:5000/log-in
Content-Type: application/json

{
  "username": "testuser4",
  "password": "testuser2"
}

###

GET http://localhost:5000/workout/id=1
Accept: application/json

###

GET http://localhost:5000/workouts/2023-12-10/2023-12-20
Accept: application/json


###

GET http://localhost:5000/allworkouts
Accept: application/json

###

